version: '3.7'

services:
  mongodb-test:
    env_file: .env
    image: mongo:4.2.3
    container_name: mongodb-test
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}
    networks:
      - local_ISEC_test

  server-test:
    env_file: .env
    image: ${DOCKER_HUB_USERNAME}/isec-backend:${CI_COMMIT_SHORT_SHA}
    container_name: server-test
    depends_on:
      - mongodb-test
    environment:
      DATABASE_URL: mongodb://${MONGO_INITDB_USERNAME}:${MONGO_INITDB_PASSWORD}@mongodb-test:27017/${MONGO_INITDB_DATABASE}
      NODE_ENV: DEVELOPMENT
      PORT: ${NODE_PORT}
      JWTSECRET: ${JWTSECRET}
      SALTROUNDS: ${SALTROUNDS}
      WAIT_HOSTS: mongodb-test:27017
      WAIT_BEFORE_HOSTS: 10
    entrypoint: sh -c "/wait && yarn test"
    networks:
      - local_ISEC_test

networks:
  local_ISEC_test: